name: book_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  barcode_image: ^2.0.3
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  image: ^4.1.3
  orm: ^3.4.4
  pdf: ^3.10.6
  # printing: ^5.11.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
